# CMake generated Testfile for 
# Source directory: D:/work/dlog/sdk/glog
# Build directory: D:/work/dlog/sdk/glogBuild64
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(demangle "D:/work/dlog/sdk/glogBuild64/Debug/demangle_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(demangle "D:/work/dlog/sdk/glogBuild64/Release/demangle_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(demangle "D:/work/dlog/sdk/glogBuild64/MinSizeRel/demangle_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(demangle "D:/work/dlog/sdk/glogBuild64/RelWithDebInfo/demangle_unittest.exe")
else()
  add_test(demangle NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(logging "D:/work/dlog/sdk/glogBuild64/Debug/logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(logging "D:/work/dlog/sdk/glogBuild64/Release/logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(logging "D:/work/dlog/sdk/glogBuild64/MinSizeRel/logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(logging "D:/work/dlog/sdk/glogBuild64/RelWithDebInfo/logging_unittest.exe")
else()
  add_test(logging NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(signalhandler "D:/work/dlog/sdk/glogBuild64/Debug/signalhandler_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(signalhandler "D:/work/dlog/sdk/glogBuild64/Release/signalhandler_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(signalhandler "D:/work/dlog/sdk/glogBuild64/MinSizeRel/signalhandler_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(signalhandler "D:/work/dlog/sdk/glogBuild64/RelWithDebInfo/signalhandler_unittest.exe")
else()
  add_test(signalhandler NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(stacktrace "D:/work/dlog/sdk/glogBuild64/Debug/stacktrace_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(stacktrace "D:/work/dlog/sdk/glogBuild64/Release/stacktrace_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(stacktrace "D:/work/dlog/sdk/glogBuild64/MinSizeRel/stacktrace_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(stacktrace "D:/work/dlog/sdk/glogBuild64/RelWithDebInfo/stacktrace_unittest.exe")
else()
  add_test(stacktrace NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(stl_logging "D:/work/dlog/sdk/glogBuild64/Debug/stl_logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(stl_logging "D:/work/dlog/sdk/glogBuild64/Release/stl_logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(stl_logging "D:/work/dlog/sdk/glogBuild64/MinSizeRel/stl_logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(stl_logging "D:/work/dlog/sdk/glogBuild64/RelWithDebInfo/stl_logging_unittest.exe")
else()
  add_test(stl_logging NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(symbolize "D:/work/dlog/sdk/glogBuild64/Debug/symbolize_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(symbolize "D:/work/dlog/sdk/glogBuild64/Release/symbolize_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(symbolize "D:/work/dlog/sdk/glogBuild64/MinSizeRel/symbolize_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(symbolize "D:/work/dlog/sdk/glogBuild64/RelWithDebInfo/symbolize_unittest.exe")
else()
  add_test(symbolize NOT_AVAILABLE)
endif()
