# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget glog::glog)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target glog::glog
add_library(glog::glog SHARED IMPORTED)

set_target_properties(glog::glog PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "GLOG_NO_ABBREVIATED_SEVERITIES;GOOGLE_GLOG_DLL_DECL=__declspec(dllimport);GOOGLE_GLOG_DLL_DECL_FOR_UNITTESTS=__declspec(dllimport)"
  INTERFACE_INCLUDE_DIRECTORIES "D:/Work/dlog/sdk/glogBuild32;D:/Work/dlog/sdk/glog/src;D:/Work/dlog/sdk/glog/src/windows"
)

# Import target "glog::glog" for configuration "Debug"
set_property(TARGET glog::glog APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(glog::glog PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Work/dlog/sdk/glogBuild32/Debug/glogd.lib"
  IMPORTED_LOCATION_DEBUG "D:/Work/dlog/sdk/glogBuild32/Debug/glogd.dll"
  )

# Import target "glog::glog" for configuration "Release"
set_property(TARGET glog::glog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(glog::glog PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Work/dlog/sdk/glogBuild32/Release/glog.lib"
  IMPORTED_LOCATION_RELEASE "D:/Work/dlog/sdk/glogBuild32/Release/glog.dll"
  )

# Import target "glog::glog" for configuration "MinSizeRel"
set_property(TARGET glog::glog APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(glog::glog PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Work/dlog/sdk/glogBuild32/MinSizeRel/glog.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Work/dlog/sdk/glogBuild32/MinSizeRel/glog.dll"
  )

# Import target "glog::glog" for configuration "RelWithDebInfo"
set_property(TARGET glog::glog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(glog::glog PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Work/dlog/sdk/glogBuild32/RelWithDebInfo/glog.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Work/dlog/sdk/glogBuild32/RelWithDebInfo/glog.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
